### PR TITLE
BZ-1192591

### PR DESCRIPTION
**Pull request by wprice**
Added new 1.1 version for IIOP schema
  Removed ejb-name from iiopConfigTypeElement

Fixes numerous bugs dealing with IIOP and ejb-name in incorrect location.

### CODE REVIEW

**Comment by wolfc** [comment]
Needs:
* Test case for xsd
* Test case for with a sample xml
* Likely needs a new parser

**Comment by wprice** [comment]
There may be some confusion here. The test case and new parser will provided with the PR-901186 which will be combined.

**Comment by wolfc** [comment]
I think we are thinking the same. It's just to ensure the proper state of this PR is reflected as to why it isn't going to merged at this point.

**Comment by wprice** [comment]
Got it, thanks for the record of where this is headed. Your right, good to keep it marked.

**Pull request closed without merging**
