### PR TITLE
NOBZ ValidationHelper improvements for schema loading etc

### PR DESCRIPTION
**Pull request by wprice**
ValidationHelper improvements to allow for loading XSD resources
  Allows loading from JSON format
  Enables better IIOP testing

### CODE REVIEW

**Comment by wolfc** [comment]
It needs something for the custom xsds. Right now if I change for example ts-test.xsd to something invalid it is not detected any more in the test.

**Comment by wprice** [comment]
I'm sorry, I'm not understanding. This is primarily done to assist in moving the hardcoded xsd names out of the files and into a external file that we can read and add to. Could you explain your last comment?

**Comment by wolfc** [comment]
I don't see ts-test.xsd listed in system-map.json. So it appears it is no longer used for validation.

**Comment by wprice** [comment]
It will be, it's manually added in the ParserHelper for now similar to how we did it before, I just need to determine how we are going to map/handle this as the system only hands me a limited amount of information when it goes to resolve that xsd. I'm looking at it further. I wanted to get the work I had committed before I started work on the IIOP stuff which is going to require validation and what not. In other words, I wanted my improvements in place and rather than check in a ton of stuff, I thought it would be better to check stuff in in incremental improvements.

**Comment by wolfc** [comment]
Ah I see it now, it does detect the failure, but the test does not fail anymore:
```
Warning: validation was turned on but an org.xml.sax.ErrorHandler was not set, which is probably not what is desired.  Parser will use a default ErrorHandler to print the first 0  errors.  Please call the setErrorHandler method to fix this.
Error: URI=null Line=52: cvc-complex-type.2.4.a: Invalid content was found starting with element 'tx:timeout'. One of '{"http://java.sun.com/xml/ns/javaee":method, "urn:tx-timeout-test":timeoutX}' is expected.
```

**Comment by wprice** [comment]
Grr...ok, forgot to set the error handler. Will fix.

**Comment by wprice** [comment]
Going to resubmit with another PR. Closing for now.

**Pull request closed without merging**
