### PR TITLE
FIxing build and adding test on the schema.

### PR DESCRIPTION
**Pull request by ehsavoie**
@jfclere you can't merge typo changes in released schemas :(

### CODE REVIEW

**Comment by rhusar** [comment]
@ehsavoie Note really, the test is wrong, the idea that the schemas are immutable is wrong.

**Comment by ehsavoie** [comment]
Hum having released schemas changing can lead to a nightmare. Also I need  a fix version upgrade so it is better to put those in there

**Comment by rhusar** [comment]
Could you please elaborate on what the nightmare would be? Just to make sure, the changes we are talking here are *only* changing xs:documentation, so in no way are affecting validation.

**Comment by rhusar** [comment]
> Hum having released schemas changing

Needless to say, we change schemas delivered in WildFly releases. The schemas are delivered with every release.

**Comment by wolfc** [comment]
The are not. Schemas are published. Once published can never be changed anymore.

**Comment by wolfc** [comment]
http://www.jboss.org/schema/jbossas/
Tools are allowed to download and cache those schemas. Similar to maven central artifacts.

**Pull request merged**
