### PR TITLE
[JBMETA-398] The jboss-web_7_1.xsd and 7.2.xsd file cause validation errors in Eclipse

### PR DESCRIPTION
**Pull request by rnetuka**
https://issues.jboss.org/browse/JBMETA-398

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1208342

### CODE REVIEW

**Comment by wolfc** [comment]
- [ ] Testcase

**Comment by rnetuka** [comment]
This is only a simple change in XML schema. Creating a test case for it would be overkill.

**Comment by elguardian** [comment]
you need version bump for something like this. You have created an incompatibility for the exact same schema

**Comment by rnetuka** [comment]
@elguardian this is meant as a fix. The original schema was incorrect. See the BZ.

By the way, the fix is based on these changes posted earlier: https://github.com/jboss/metadata/pull/78

**Pull request merged**
